spring.application.name=MyProject
server.port=80
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://ep-odd-scene-a2mr6slc.eu-central-1.aws.neon.tech:5432/MyProject?user=Adam&password=Wt4uQKgkMlD1&sslmode=require&ssl=truesslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=Adam
spring.datasource.password=Wt4uQKgkMlD1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
hibernate.transaction.jta.platform=enable

logging.level.com.MyProject===INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adamgubola@gmail.com	
spring.mail.password=tsot lygw jguc qvyt
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.smtp.ssl.protocols=TLSv1.2
support.mail=adamgubola@gmail.com